### ISSUE TITLE
Error when trying to edit a blog

### ISSUE THREAD

**Issue by Heyula** [mambax7/myiframe#4]
modules/myiframe/blocks/myiframe_iframe.php hattı 56

![a1](https://user-images.githubusercontent.com/5504159/160358427-e95ae604-6274-4321-8e0f-5fb117229217.jpg)

**Comment by mambax7** [comment]
This should fix it: https://github.com/mambax7/myiframe/commit/2596792859cfd8bde14a91f3e57663d2f7fec7b3

Thanks for the reporting!
